<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Application
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="">
    <title><?php echo $this->escapeHtml($this->translate('Admin panel')); ?> - SoonCms</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />


    <?php echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8'); ?>

  <!-- Le styles -->
	<?php
	echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
			->prependStylesheet($this->basePath() . '/backend/css/main.css')
	?>
<style>
<!--
.mainright a,.maincontent a:visited{color:#F00; text-decoration:none;}
.mainright a:hover{color:#900; text-decoration:underline;}
.mainleft a,.mainleft a:visited{color:#06C; text-decoration:none;}
.mainleft a:hover{color:#00F; text-decoration:underline;}
-->
</style>
<script> 
/*屏蔽所有的js错误*/
function killerrors() {return true;}
window.onerror = killerrors;
function logout(){
	if (confirm("您确定要退出控制面板吗？"))
	top.location = '<?php echo $this->url('config/user/logout'); ?>';
	return false;
}
<?php 
  if($this->admin())
  {
  	$username = $this->admin()->getlogin();
  	$rolename = $this->admin()->getRole()->getName();
  }
?>
</script>
</head>
<body style="font-size:12px; padding-bottom:0;" onLoad="version_msg();">
<div id="sysinfobox" class="sysinfobox" style="display:none;">
	<script>
    	setTimeout("document.getElementById('sysinfobox').style.display='none'",10000);
    </script>
	<div class="sysinfoboxtop" id="sysinfoboxtop"><strong style="float:left;margin-left:10px;">友情提醒</strong><span style="float:left;">(10秒后自动退出)</span><span style="float:right;margin-right:10px;"><a href="#" onclick="javascript:document.getElementById('sysinfobox').style.display='none';">[关闭]</a></span></div> 
</div>
<div style="height:455px; ">
<div class="mainleft">
	<div class="maininfo" style="height:130px">
    	<div class="mainboxtop"><h6>我的信息</h6></div>
        <div class="maincontent">
        <p>您好，<?php echo $username;?>　　[<a href="#" onClick="logout();">更换帐户</a>]</p>
        <p>您的登陆帐户，<?php echo $username;?></p>
		<p>所属角色：<?php echo $rolename;?></p>
        </div>
    </div>
    <div class="maininfo" style="height:170px">
    	<div class="mainboxtop"><h6>快捷方式</h6></div>
        <div class="maincontent">
        <table width="100%">
        	<tr>
            	<td align="center" width="33%">
                	<a href="index.php?M=admin_resume"><img width="40" height="35" src="/backend/images/applications.png" /></a>
                </td>
                <td align="center" width="33%">
                	<a href="index.php?M=admin_news&C=group"><img width="40" height="35" src="/backend/images/folder_process.png" /></a>
                </td>
                <td align="center" width="33%">
                	<a href="index.php?M=admin_news&C=news"><img width="40" height="35" src="/backend/images/mail_edit.png" /></a>
                </td>
            </tr>
            <tr>
            	<td align="center" height="20" width="33%"><a href="index.php?M=admin_resume">简历管理</a></td>
                <td align="center" height="20" width="33%"><a href="index.php?M=admin_news&C=group">新闻类别</a></td>
                <td align="center" height="20" width="33%"><a href="index.php?M=admin_news&C=news">发布新闻</a></td>
            </tr>
            <tr>
            	<td align="center" width="33%">
                <a href="index.php?M=admin_once"><img width="40" height="35" src="/backend/images/page_accept.png" /></a>
                </td>
                <td align="center" width="33%">
                <a href="index.php?M=index&C=index_cache"><img width="40" height="35" src="/backend/images/page_edit.png" /></a>
                </td>
                <td align="center" width="33%">
                <a href="index.php?M=config"><img width="40" height="35" src="/backend/images/process.png" /></a>
                </td>
            </tr>
            <tr>
            	<td align="center" height="20" width="33%"><a href="index.php?M=admin_once">招聘管理</a></td>
                <td align="center" height="20" width="33%"><a href="index.php?M=index&C=index_cache">生成首页静态</a></td>
                <td align="center" height="20" width="33%"><a href="index.php?M=config">系统管理</a></td>
            </tr>
        </table>
        </div>
    </div>
    <div class="maininfo" style="">
    	<div class="mainboxtop"><h6>开发团队</h6></div>
        <div class="maincontent">
        <p>SoonCms软件 开发团队：soon 等</p>
        <p>特别感谢：Huawei</p>
        <p>联系电话：13770533284</a></p>
		<p>官方网站：<a href="/" target="_blank"></a> 官方论坛：<a href="/" target="_blank"></a></p>
		<p></p>
        </div>
    </div>
</div>
<div class="mainright">
	<div class="maininfo" style="height:130px">
    	<div class="mainboxtop"><h6>网站信息</h6></div>
        <div class="maincontent">
        <div style="width:200px; float:left;clear:left; margin-bottom:5px;">今日个人注册/总数:{yun:}$user_num{/yun} / {yun:}$usernum_all{/yun}</div>        <div style="width:250px;float:right; clear:right; margin-bottom:5px;">今日简历数/总数:{yun:}$resume{/yun} / {yun:}$resume_all{/yun}</div>
        <div style="width:200px; float:left;clear:left; margin-bottom:5px;">今日企业注册/总数:{yun:}$com_nums{/yun} / {yun:}$comnum_all{/yun}</div>        <div style="width:250px; float:right;clear:right; margin-bottom:5px;">今日职位数/总数:{yun:}$job{/yun} / {yun:}$job_all{/yun}</div>
        <div style="width:200px; float:left;clear:left; margin-bottom:5px;">今日新闻条数/总数:{yun:}$news{/yun} / {yun:}$news_all{/yun}</div>
        <div style="width:250px; float:right;clear:right; margin-bottom:5px;">广告总数:{yun:}$ad_all{/yun}</div>
        <div style="width:200px; float:left;clear:left; margin-bottom:5px;"><A href="index.php?M=admin_once&status=0">待审核一句话招聘:</A>{yun:}$once{/yun}</div>   
        <div style="width:250px; float:right;clear:right; margin-bottom:5px;"><A href="index.php?M=link&state=0">待审核链接:</A>{yun:}$link{/yun}</div>
		 <div style="width:200px; float:left;clear:left; margin-bottom:5px;"><A href="index.php?M=admin_company_job&state=4">待审核职位:</A>{yun:}$com_job_4{/yun}</div>
		 <div style="width:250px; float:right;clear:right; margin-bottom:5px;"><A href="index.php?M=comcert&status=2">待认证的企业:</A>{yun:}$com_cert_2{/yun}</div>
		 <div style="width:200px; float:left;clear:left; margin-bottom:5px;"><A href="index.php?M=company_order&order_state=">待处理的订单:</A>{yun:}$com_order_3{/yun}</div>
        </div>
    </div>
    <div class="maininfo" style="height:170px">
    	<div class="mainboxtop"><h6>系统信息</h6></div>
        <div class="maincontent">
        <p style="float:left;">SoonCms程序版本：1.0 [ <div id="version_msg" style="float:left;">无须更新!</div>]</p>
		<p style="clear:both;">服务器软件：<?php echo $this->soft;?></p>
        <p>可用空间(磁盘区)：<?php echo $this->kongjian;?>&nbsp;M</p>
		<p>MySQL 版本：<?php echo $this->banben;?></p>
		<p>用户 - 服务器：<?php echo $this->yonghu;?> - <?php echo $this->server;?></p>
        </div>
    </div>
    <div class="maininfo" style="height:105px;">
    	<div class="mainboxtop"><h6>授权信息</h6></div>
        <div class="maincontent">
        <p>SoonCms程序版本： 1.0 [<a href="/">技术支持与服务</a>]</p>
        <p>咨询QQ： 297461244</p>
        <div style="display:none;">
		<p>授权类型：未授权（<a href="/">点击购买</a>）</p>
		<p>序列号：未激活（<a href="/">点击激活</a>）</p>
        </div></div>
    </div>
</div>
</div>
</body>
</html>
